"""Models package — re-exports all public model classes from v1 and v2."""

from __future__ import annotations

from seedr_api.models.common import APIVersion, _safe_parse, _safe_parse_list
from seedr_api.models.v1 import (
    V1AccountSettings,
    V1AddFolderResult,
    V1DeleteResult,
    V1Device,
    V1DeviceCode,
    V1FetchFileResult,
    V1FileItem,
    V1FolderContents,
    V1FolderItem,
    V1MemoryBandwidth,
    V1RefreshToken,
    V1RenameResult,
    V1SearchResult,
    V1TokenResponse,
    V1TorrentItem,
    V1WishlistItem,
)
from seedr_api.models.v2 import (
    V2AccountInfo,
    V2AccountSettings,
    V2AddTaskResult,
    V2ArchiveInit,
    V2DeviceCode,
    V2DownloadURL,
    V2FileInfo,
    V2FilePresentations,
    V2FolderContents,
    V2FolderItem,
    V2FolderPresentations,
    V2PresentationURLs,
    V2Quota,
    V2SubtitleInfo,
    V2SubtitlesList,
    V2Task,
    V2TasksResponse,
    V2TokenResponse,
    V2WishlistItem,
    V2WishlistTask,
)

__all__ = [
    "APIVersion",
    "V1AccountSettings",
    "V1AddFolderResult",
    "V1DeleteResult",
    "V1Device",
    "V1DeviceCode",
    "V1FetchFileResult",
    "V1FileItem",
    "V1FolderContents",
    "V1FolderItem",
    "V1MemoryBandwidth",
    "V1RefreshToken",
    "V1RenameResult",
    "V1SearchResult",
    "V1TokenResponse",
    "V1TorrentItem",
    "V1WishlistItem",
    "V2AccountInfo",
    "V2AccountSettings",
    "V2AddTaskResult",
    "V2ArchiveInit",
    "V2DeviceCode",
    "V2DownloadURL",
    "V2FileInfo",
    "V2FilePresentations",
    "V2FolderContents",
    "V2FolderItem",
    "V2FolderPresentations",
    "V2PresentationURLs",
    "V2Quota",
    "V2SubtitleInfo",
    "V2SubtitlesList",
    "V2Task",
    "V2TasksResponse",
    "V2TokenResponse",
    "V2WishlistItem",
    "V2WishlistTask",
    "_safe_parse",
    "_safe_parse_list",
]
